version: '3'
services:
  www:
    image: php:apache
    volumes:
      - "./:/var/www/html"
    ports:
      - 8080:80
      - 443:443 #SSL Service
    command: >
      bash -c "docker-php-ext-install mysqli && apache2-foreground"
  db: 
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=dbback #Ändern
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=password # this should live in a env var
      - MYSQL_ALLOW_EMPTY_PASSWORD=1 # equivalent to True
    volumes:
      - "./db:/docker-entrypoint-initdb.d" # this is how we persist a sql db even when container stops
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306

